export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DB_UNAVAILABLE: "DB_UNAVAILABLE",
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  NO_QUESTIONS: "NO_QUESTIONS"
} as const;
