export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  LOCAL_DB_FAILED: "LOCAL_DB_FAILED",
  INVALID_ANSWER: "INVALID_ANSWER",
  EMPTY_QUIZ: "EMPTY_QUIZ"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
